#################################################################################
# The Institute for the Design of Advanced Energy Systems Integrated Platform
# Framework (IDAES IP) was produced under the DOE Institute for the
# Design of Advanced Energy Systems (IDAES).
#
# Copyright (c) 2018-2026 by the software owners: The Regents of the
# University of California, through Lawrence Berkeley National Laboratory,
# National Technology & Engineering Solutions of Sandia, LLC, Carnegie Mellon
# University, West Virginia University Research Corporation, et al.
# All rights reserved.  Please see the files COPYRIGHT.md and LICENSE.md
# for full copyright and license information.
#################################################################################

[logging]
level = "INFO"

[data]
data_path = "../gtep/data/123_Bus_Resil_Week"
stages = 1
num_reps = 4
num_commit = 2
num_dispatch = 1
duration_representative_period = 2

# Extra Texas/resilience case-study preprocessing
load_scaling_path = "../gtep/data/123_Bus_Resil_Week/ERCOT-Adjusted-Forecast.xlsb"
apply_texas_case_study_updates = true

[cost_data]
enabled = false

[model]
include_investment = true
include_commitment = true
include_redispatch = true
scale_loads = true
scale_texas_loads = true
transmission = true
storage = false
flow_model = "DC"
advanced_hydro = false

[transformations]
bound_pretransformation = false
bigm = true

[solver]
solver_name = "gurobi_direct"
tee = true
log_file = "basic_logging.log"
mip_gap = 0.001

[results]
dir_name = "results"
save_json = true
value_threshold = 1e-3

[plots]
enabled = false
case_json = "combined"
plot_type = "all"
stackgraph = false
