[logging]
level = "INFO"

[data]
data_path = "../gtep/data/Texas_2000"
stages = 3
num_reps = 4
len_reps = 24
num_commit = 24
num_dispatch = 1
duration_dispatch = 60

# Extra Texas case-study preprocessing
load_scaling_path = "../gtep/data/Texas_2000/ERCOT-Adjusted-Forecast.xlsb"
apply_texas_case_study_updates = true

[cost_data]
enabled = false

[model]
include_investment = true
include_commitment = true
include_redispatch = true
scale_loads = false
scale_texas_loads = true
transmission = true
storage = false
flow_model = "DC"
advanced_hydro = false

[transformations]
bound_pretransformation = false
bigm = true

[solver]
name = "gurobi"
tee = true
log_file = "t2k_logging.log"
mip_gap = 0.01

[results]
dir_name = "results"
value_threshold = 1e-3
