#################################################################################
# The Institute for the Design of Advanced Energy Systems Integrated Platform
# Framework (IDAES IP) was produced under the DOE Institute for the
# Design of Advanced Energy Systems (IDAES).
#
# Copyright (c) 2018-2026 by the software owners: The Regents of the
# University of California, through Lawrence Berkeley National Laboratory,
# National Technology & Engineering Solutions of Sandia, LLC, Carnegie Mellon
# University, West Virginia University Research Corporation, et al.
# All rights reserved.  Please see the files COPYRIGHT.md and LICENSE.md
# for full copyright and license information.
#################################################################################

# Example of full GTEP configuration file for the 5 bus case

# Run with:
#    python driver_from_config.py --config examples/config_5bus_jsc.toml

[logging]
level = "INFO"

[data]
data_path = "./data/5bus_jsc"
stages = 2
num_reps = 2
len_reps = 1
num_commit = 6
num_dispatch = 2
duration_dispatch = 60

[cost_data]
enabled = false

[model]
include_investment = true
include_commitment = true
include_redispatch = true
scale_loads = true
transmission = true
storage = false
flow_model = "DC"
advanced_hydro = false

[transformations]
bound_pretransformation = true
bigm = true

[solver]
name = "gurobi"
tee = false

[results]
dir_name = "results"
value_threshold = 1e-3
